###############################################################################
# Makefile for the project cdctiny
###############################################################################

## General Flags
PROJECT = cdctiny

MCU = attiny45
#MCU = attiny85

##  Fuse bits:
##   Xtal    		FF 6E-FF
##   PLL(16.5MHz)	FF 6E-F1

CLK = 12000000UL
#CLK = 15000000UL
#CLK = 16000000UL
#CLK = 16500000UL		## PLL
#CLK = 18000000UL
#CLK = 20000000UL

TARGET = cdctiny.elf
CC = avr-gcc

## Options common to compile, link and assembly rules
COMMON = -mmcu=$(MCU) -DF_CPU=$(CLK)

## UART_INVERT reverses the polarity of TXD and RXD to
## connect to RS-232C directly.
#COMMON += -DUART_INVERT

## Compile options common for all C compilation units.
CFLAGS = $(COMMON)
CFLAGS += -Wall -gdwarf-2 -Os -fsigned-char
CFLAGS += -MD -MP -MT $(*F).o -MF dep/$(@F).d 

## Assembly specific flags
ASMFLAGS = $(COMMON)
ASMFLAGS += $(CFLAGS)
ASMFLAGS += -x assembler-with-cpp -Wa,-gdwarf2

## Linker flags
LDFLAGS = $(COMMON)
LDFLAGS += 


## Intel Hex file production flags
HEX_FLASH_FLAGS = -R .eeprom -R .fuse -R .lock -R .signature

HEX_EEPROM_FLAGS = -j .eeprom
HEX_EEPROM_FLAGS += --set-section-flags=.eeprom="alloc,load"
HEX_EEPROM_FLAGS += --change-section-lma .eeprom=0 --no-change-warnings


## Include Directories
INCLUDES =
INCLUDES = -I".." -I"../../usbdrv" -I"../../libs-device"

## Objects that must be built in order to link
OBJECTS = usbdrv.o usbdrvasm.o oddebug.o osccal.o sw-uart-asm.o sw-uart.o main.o

## Objects explicitly added by the user
LINKONLYOBJECTS = 

## Build
all: $(TARGET) cdctiny45.hex cdctiny45.eep cdctiny45.lss size

## Compile
usbdrv.o: ../../usbdrv/usbdrv.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

usbdrvasm.o: ../../usbdrv/usbdrvasm.S
	$(CC) $(INCLUDES) $(ASMFLAGS) -c  $<

oddebug.o: ../../usbdrv/oddebug.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

osccal.o: ../../libs-device/osccal.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

sw-uart-asm.o: ../sw-uart-asm.S
	$(CC) $(INCLUDES) $(ASMFLAGS) -c  $<

sw-uart.o: ../sw-uart.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

main.o: ../main.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

##Link
$(TARGET): $(OBJECTS)
	 $(CC) $(LDFLAGS) $(OBJECTS) $(LINKONLYOBJECTS) $(LIBDIRS) $(LIBS) -o $(TARGET)

%.hex: $(TARGET)
	avr-objcopy -O ihex $(HEX_FLASH_FLAGS)  $< $@

%.eep: $(TARGET)
	-avr-objcopy $(HEX_EEPROM_FLAGS) -O ihex $< $@ || exit 0

%.lss: $(TARGET)
	avr-objdump -h -S $< > $@

size: ${TARGET}
	@echo
	@avr-size -C --mcu=${MCU} ${TARGET}

## Clean target
.PHONY: clean
clean:
	-rm -rf $(OBJECTS) cdctiny45.elf dep/* cdctiny45.hex cdctiny45.eep cdctiny45.lss

## Other dependencies
-include $(shell mkdir dep 2>/dev/null) $(wildcard dep/*)

